name: CI Pipeline
 
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 80:80
          - 5000:5000
          - 11434:11434
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Setup Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y
 
      - name: Build and start services
        working-directory: ../frontend-backend
        run: docker-compose up --build -d
 
      - name: Test Flask API
        run: |
          sleep 15
          curl --fail http://localhost:5000 || exit 1
 
      - name: Test Ollama API
        run: |
          sleep 15
          curl --fail http://localhost:11434 || exit 1
 
      - name: Shutdown Docker Compose
        working-directory: ../frontend-backend
        run: docker-compose down