name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 80:80
          - 5000:5000
          - 11434:11434

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List current directory
        run: ls -al

      - name: Setup Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and start services
        run: docker-compose up --build -d

      - name: Shutdown Docker Compose
        run: docker-compose down