name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 80:80
          - 5000:5000
          - 11434:11434

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape de diagnostic pour lister les fichiers et répertoires actuels
      - name: List current directory
        run: ls -al  # Affiche tous les fichiers et répertoires dans le répertoire actuel

      - name: List compose-tp-final directory
        run: ls -al ../compose-tp-final || echo "compose-tp-final not found"  # Affiche le contenu ou un message d'erreur

      - name: Setup Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Build and start services
        working-directory: ../compose-tp-final  # Si le chemin est confirmé, cette étape fonctionnera
        run: docker-compose up --build -d

      - name: Test Flask API
        run: |
          sleep 15
          curl --fail http://localhost:5000 || exit 1

      - name: Test Ollama API
        run: |
          sleep 15
          curl --fail http://localhost:11434 || exit 1

      - name: Shutdown Docker Compose
        working-directory: ../compose-tp-final  # Même chemin pour docker-compose
        run: docker-compose down
